### PR TITLE
Add new transition type (fade) and some little improvements

### PR DESCRIPTION
**Pull request by xxcram**
In my last project I had to use fade transition in a slider.
Glide.js is just easy and works fine, so I added a new transition type.

### CODE REVIEW

**Comment by xxcram** [comment]
Thanks, great stuff

**Comment by ChaseGiunta** [comment]
This is actually completely broken. There are some CSS edits you would have to make in order for this to work- the merged PR does not include any.

**Comment by xxcram** [comment]
Really? I never had problems until now and I used it multiple times.
Which styles you had to edit?

**Comment by magicspon** [comment]
Do you have an example of glide using a fade transition, or can you point me to any docs.

Thanks

**Comment by CorySchulz** [comment]
Can someone point out the fade code from 2.0 so we can migrate it to 3.0?

**Pull request merged**
